name: Update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 */3 * *'  # Runs at 00:00 UTC every 3 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: update things
      run: |
        npm install
        npm run update
    - name: Commit files
      run: |
        git config --local user.email "frto027-github-actions[bot]@users.noreply.github.com"
        git config --local user.name "frto027-github-actions[bot]"
        git add .
        ls database
        git commit -a -m "Auto db update" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
